version: '3.7'

services:
  master:
    hostname: master
    container_name: master
    image: jungfrau70/centos7
    build:
      context: ..
      dockerfile: Dockerfile.spark
    restart: always
    networks:
      netgroup:
        ipv4_address: 172.18.0.21
    ports:
      - "9090:8080"
      - "8088:8088"
      - "7077:7077"
      - "18080:18080"
    volumes:
      # Just specify a path and let the Engine create a volume
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ~/.ssh:/root/.ssh:ro
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
      - ../../dags:/home/jovyan/dags
    privileged: true
    entrypoint: ["/usr/sbin/init"]
    # command: |
    #   -["jupyter", "lab", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    cap_add:
      - NET_ADMIN
    env_file:
      - cluster.env


networks:
  netgroup:
    name: netgroup
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
